# Generated by Django 2.1.5 on 2019-02-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecohome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerproduct',
            name='banner_product_category',
            field=models.CharField(choices=[('WOMEN COLLECTION 2019 ', 'WOMEN'), ('MALE COLLECTION 2019 ', 'MALE')], max_length=30),
        ),
    ]
