# Generated by Django 2.1.5 on 2019-02-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecohome', '0003_homeproductdisplay'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=200)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(max_length=70)),
                ('phone_number', models.IntegerField()),
            ],
        ),
    ]
