# Generated by Django 2.1.5 on 2019-02-12 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecohome', '0004_userdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDetails',
            new_name='UserDetail',
        ),
    ]
