# Generated by Django 2.1.5 on 2019-02-14 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcart',
            name='cart_product_image',
        ),
        migrations.RemoveField(
            model_name='productcart',
            name='cart_product_name',
        ),
        migrations.RemoveField(
            model_name='productcart',
            name='cart_product_price',
        ),
    ]
