# Generated by Django 2.1.5 on 2019-02-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20190214_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcart',
            name='cart_product_buyer',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
    ]
