# Generated by Django 2.1.5 on 2019-02-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_image', models.ImageField(upload_to='ProImg')),
                ('product_description', models.CharField(max_length=100)),
                ('product_price', models.IntegerField()),
                ('product_tage', models.CharField(choices=[('New', 'NEW'), ('Sale', 'SALE'), ('Premiere', 'PREMIERE')], max_length=10)),
            ],
        ),
    ]
