# Generated by Django 2.1.5 on 2019-02-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190212_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image_second',
            field=models.ImageField(default=True, upload_to='ProImg'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_image_third',
            field=models.ImageField(default=True, upload_to='ProImg'),
            preserve_default=False,
        ),
    ]
