# Generated by Django 2.1.5 on 2019-02-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20190212_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_addition_detail',
            field=models.TextField(blank=True),
        ),
    ]
