# Generated by Django 2.1.5 on 2019-02-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_product_addition_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_eye_catcher',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
