# Generated by Django 2.1.5 on 2019-02-13 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_product_eye_catcher'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_reviewer_name', models.CharField(max_length=50)),
                ('product_review', models.TextField()),
            ],
        ),
    ]
