# Generated by Django 2.1.5 on 2019-02-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('SUNGLASSES', 'SUNGLASSES'), ('DRESSES', 'DRESSES'), ('FOOTWEAR', 'FOOTWEAR'), ('WATCHES', 'WATCHES'), ('BAGS', 'BAGS')], default=True, max_length=15),
            preserve_default=False,
        ),
    ]
