# Generated by Django 2.1.5 on 2019-02-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_color_by_user',
            field=models.CharField(blank=True, choices=[('RED', 'RED'), ('BLUE', 'BLUE'), ('GREEN', 'GREEN')], max_length=10),
        ),
    ]
