# Generated by Django 2.1.5 on 2019-02-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_product_color_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_gernder',
            field=models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], default=True, max_length=10),
            preserve_default=False,
        ),
    ]
