# Generated by Django 2.1.5 on 2019-02-13 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_product_gernder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_gernder',
            new_name='product_gender',
        ),
    ]
