# Generated by Django 2.1.5 on 2019-02-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_quantity',
            field=models.IntegerField(blank=True, default='1', null=True),
        ),
    ]
