# Generated by Django 2.1.5 on 2019-02-15 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20190214_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_quantity',
            new_name='product_quantity_total_price',
        ),
    ]
